name: GithubActions Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Develop account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN_DEVELOP }}
          aws-region: ap-southeast-2
          role-duration-seconds: 1200
          role-session-name: GitHubActions
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform plan -var-file="values/develop.tfvars"
      - run: terraform apply -var-file="values/develop.tfvars"
  sync:
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Develop account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN_DEVELOP }}
          aws-region: ap-southeast-2
          role-duration-seconds: 1200
          role-session-name: GitHubActions
      - name: Copy files to the develop bucket
        run: |
          aws s3 sync frontend s3://${stdout}
